replicaCount: 2

image:
  repository: hextris
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations: {}
  # Values set by default for local test
  host: hextris.local
  paths:
    - path: /
      pathType: Prefix

